on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - "master"

jobs:
  ci:
    runs-on: host
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile csproj
        run: |
          dotnet build "./src/ShouldlyFluentassertionsBridge.csproj" -c Release

      - name: list sources
        run: |
          cp "/home/crashdummy/.nuget/NuGet/NuGet.Config" .
          dotnet nuget list source

      - name: PacknPush
        if: ${{ github.event_name == 'push' }}
        run: |
          dotnet pack "./src/ShouldlyFluentassertionsBridge.csproj" -c Release -p:PackageVersion="${{ github.ref_name }}" -p:PackageID="Codepotatoes.ShouldlyFluentassertionsBridge" -o .
          dotnet nuget push *.nupkg -s "https://git.codepotatoes.de/api/packages/Packages/nuget/index.json" -k "${{ secrets.NUGET_API_KEY }}"
          dotnet nuget push *.nupkg -s "https://api.nuget.org/v3/index.json" -k "${{ secrets.NUGETORG_API_KEY }}"

